/**
 * The one swappable adapter (§2).
 *
 * Calling code says `api.get('/api/auth/me')`. Today MSW intercepts. Tomorrow
 * the same fetch hits a real Express backend. No call site changes.
 *
 * Envelope contract (§9):
 *   Success: 2xx  { data: T }
 *   Error:   4xx  { error: { code, message, details? } }
 */

export interface ApiError extends Error {
  status: number;
  code: string;
  details?: unknown;
}

function makeError(status: number, code: string, message: string, details?: unknown): ApiError {
  const err = new Error(message) as ApiError;
  err.status = status;
  err.code = code;
  err.details = details;
  return err;
}

async function request<T>(path: string, init: RequestInit = {}): Promise<T> {
  let res: Response;
  // FormData must set its own Content-Type: the boundary is generated by the
  // browser, and declaring application/json here would make the body
  // unparseable on the server.
  const isForm = init.body instanceof FormData;
  try {
    res = await fetch(path, {
      ...init,
      credentials: 'include',
      headers: {
        ...(isForm ? {} : { 'Content-Type': 'application/json' }),
        Accept: 'application/json',
        ...(init.headers ?? {}),
      },
    });
  } catch {
    // fetch only rejects for transport failures — the backend is down, the
    // proxy has nothing to talk to, or CORS blocked the response. There is
    // no HTTP status here, so status 0 marks "never reached the server" and
    // pages can tell it apart from a real 4xx.
    throw makeError(0, 'network_error',
      `Could not reach the API (${path}). Is the backend running? In mock mode this path may have no MSW handler.`);
  }

  if (res.status === 204) return undefined as T;

  const text = await res.text();
  let json: { data?: unknown; error?: { code: string; message: string; details?: unknown } };
  try {
    json = text ? JSON.parse(text) : {};
  } catch {
    // Not JSON — usually Vite's proxy error page or an HTML 502 from a
    // backend that is not up. Report the status we actually got rather
    // than a bare "Unexpected token <".
    throw makeError(res.status, 'bad_response',
      `The API returned a non-JSON response (HTTP ${res.status}) for ${path}.`);
  }

  if (!res.ok) {
    const e = json.error ?? { code: 'unknown', message: res.statusText };
    throw makeError(res.status, e.code, e.message, e.details);
  }
  return json.data as T;
}

/**
 * The backend is briefly unreachable while it restarts (a deploy, or the dev
 * server reloading on a code change). A read in that window fails with no
 * status, or with the proxy's non-JSON 5xx — neither is a real answer from
 * the API. So a GET is tried again a few times before the error surfaces.
 *
 * Reads only. A write is never repeated: if a POST failed mid-flight nobody
 * knows whether it landed, and retrying could create the thing twice.
 */
const TRANSIENT = (e: unknown) => {
  const x = e as Partial<ApiError>;
  if (x.status === 0) return true;
  // A real API error always carries its own { error: { code } }. A 5xx that
  // does not — an empty body or an HTML page — came from the proxy standing
  // in for a backend that is not there yet.
  return (x.status ?? 0) >= 500 && (x.code === 'bad_response' || x.code === 'unknown');
};

async function getWithRetry<T>(path: string): Promise<T> {
  // A dev reload takes ~3s (measured); a production restart can take longer.
  const waits = [300, 600, 1000, 1500, 2000];
  for (let attempt = 0; ; attempt++) {
    try {
      return await request<T>(path, { method: 'GET' });
    } catch (e) {
      if (attempt >= waits.length || !TRANSIENT(e)) throw e;
      await new Promise((r) => setTimeout(r, waits[attempt]));
    }
  }
}

export const api = {
  get: <T>(path: string) => getWithRetry<T>(path),
  post: <T>(path: string, body?: unknown) =>
    request<T>(path, { method: 'POST', body: body ? JSON.stringify(body) : undefined }),
  /** Multipart POST — the only way file bytes leave the browser. */
  postForm: <T>(path: string, form: FormData) =>
    request<T>(path, { method: 'POST', body: form }),
  patch: <T>(path: string, body?: unknown) =>
    request<T>(path, { method: 'PATCH', body: body ? JSON.stringify(body) : undefined }),
  put: <T>(path: string, body?: unknown) =>
    request<T>(path, { method: 'PUT', body: body ? JSON.stringify(body) : undefined }),
  delete: <T>(path: string) => request<T>(path, { method: 'DELETE' }),
};
