/**
 * The partnership deed — the Indian Partnership Act, 1932.
 *
 * GENERATED by scripts/build-doc-templates.mjs from the reference document.
 * Edit the reference and re-run the script rather than editing this file:
 * the clauses are a legal text, and hand-editing them here is how one goes
 * missing. The firm's own particulars are {{placeholders}}, declared as
 * fields on the document type in ../registry.ts.
 */
import type { RawBlock } from '../model';

export const PARTNERSHIP_DEED_BLOCKS: RawBlock[] = [
  {
    "key": "heading",
    "title": "PARTNERSHIP DEED",
    "variant": "title",
    "align": "center"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "This Partnership Deed is made and executed on this {{agreement_date}}, at {{place}},"
      },
      {
        "kind": "p",
        "align": "center",
        "indent": 0,
        "html": "By and between:"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "{{partner1_name}}, holding Aadhaar No. {{partner1_aadhaar}}, {{partner1_details}}, hereinafter referred to as the \"First Partner\" which expressions shall, unless repugnant to the context or meaning thereof, mean and include their respective heirs, legal representatives, executors, administrators, successors, and permitted assigns."
      },
      {
        "kind": "p",
        "align": "center",
        "indent": 0,
        "html": "AND"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "{{partner2_name}}, holding Aadhaar No. {{partner2_aadhaar}}, Son of Arumugam,"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "Residing at 373, Akamudiyar Street, Vettukottai, Orathanadu, Thanjavur – 614614,"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "hereinafter referred to as the \"Second Partner\" which expressions shall, unless repugnant to the context or meaning thereof, mean and include their respective heirs, legal representatives, executors, administrators, successors, and permitted assigns."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "The First and Second Partner shall hereinafter collectively be referred to as the “Partners” and individually as a “Partner”."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "RECITALS"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "WHEREAS the First Partner has acquired the business known as {{firm_name}} from a third party;"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "AND WHEREAS the Partners wish to carry on the said business in partnership under the terms and conditions mutually agreed;"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "NOW, THIS DEED WITNESSES AS FOLLOWS:"
      }
    ]
  },
  {
    "key": "heading",
    "title": "1. NAME OF THE FIRM",
    "variant": "subtitle",
    "align": "left"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "The partnership business shall be carried on in the name and style of “{{firm_name}}” (hereinafter referred to as the \"Firm\")."
      }
    ]
  },
  {
    "key": "heading",
    "title": "2. PRINCIPAL PLACE OF BUSINESS",
    "variant": "subtitle",
    "align": "left"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "The business of the Firm shall be carried on at:"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "{{business_address}}"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "or such other place(s) as may be mutually decided by the Partners."
      }
    ]
  },
  {
    "key": "heading",
    "title": "3. NATURE OF BUSINESS",
    "variant": "subtitle",
    "align": "left"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "The Firm shall carry on the business of {{nature_of_business}}. The Partners may expand or alter the scope of business upon mutual agreement."
      }
    ]
  },
  {
    "key": "heading",
    "title": "4. DURATION OF PARTNERSHIP",
    "variant": "subtitle",
    "align": "left"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "The partnership shall be for a fixed minimum term of five (5) years from the date of this deed. During this period, the Firm shall not be dissolved unless mutually agreed in writing by both Partners. After expiry of five years, the Firm shall continue until dissolved by mutual consent."
      }
    ]
  },
  {
    "key": "heading",
    "title": "5. CAPITAL CONTRIBUTION",
    "variant": "subtitle",
    "align": "left"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "Each Partner shall contribute {{capital_each}} towards the capital of the Firm. Additional capital, if required, shall be contributed equally or in such proportion as mutually agreed."
      }
    ]
  },
  {
    "key": "heading",
    "title": "6. PROFIT AND LOSS SHARING",
    "variant": "subtitle",
    "align": "left"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "The net profits and losses of the Firm, after providing for expenses, interest (if any), and depreciation, shall be shared equally (50:50) by the Partners."
      }
    ]
  },
  {
    "key": "heading",
    "title": "7. MANAGEMENT AND SIGNING AUTHORITY",
    "variant": "subtitle",
    "align": "left"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "a) Both Partners shall have equal rights and responsibilities in the conduct of the Firm."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "b) All decisions of importance shall be taken jointly."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "c) Both Partners shall have equal signing authority for bank operations, contracts, agreements, and legal documents of the Firm."
      }
    ]
  },
  {
    "key": "heading",
    "title": "8. DUTIES AND OBLIGATIONS OF PARTNERS",
    "variant": "subtitle",
    "align": "left"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "bullet",
        "align": "justify",
        "indent": 0,
        "html": "Each Partner shall work honestly and diligently for the benefit of the Firm."
      },
      {
        "kind": "bullet",
        "align": "justify",
        "indent": 0,
        "html": "Neither Partner shall engage in competing business without prior written consent of the other."
      },
      {
        "kind": "bullet",
        "align": "justify",
        "indent": 0,
        "html": "Neither Partner shall withdraw capital without the consent of the other."
      },
      {
        "kind": "bullet",
        "align": "justify",
        "indent": 0,
        "html": "Both Partners shall be jointly and severally liable for the debts and obligations of the Firm."
      }
    ]
  },
  {
    "key": "heading",
    "title": "9. BANK ACCOUNT",
    "variant": "subtitle",
    "align": "left"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "The Firm shall open and operate its bank account(s) in the name of the Firm with any scheduled bank. Both Partners’ signatures shall be mandatory for operations unless mutually agreed otherwise."
      }
    ]
  },
  {
    "key": "heading",
    "title": "10. ACCOUNTS & AUDIT",
    "variant": "subtitle",
    "align": "left"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "bullet",
        "align": "justify",
        "indent": 0,
        "html": "Proper books of account shall be maintained at the place of business."
      },
      {
        "kind": "bullet",
        "align": "justify",
        "indent": 0,
        "html": "<b>Accounts shall be closed on 31st March every year.</b>"
      },
      {
        "kind": "bullet",
        "align": "justify",
        "indent": 0,
        "html": "A Balance Sheet and Profit &amp; Loss Account shall be prepared, and profits distributed accordingly."
      },
      {
        "kind": "bullet",
        "align": "justify",
        "indent": 0,
        "html": "The accounts may be audited, if required, by a mutually appointed auditor."
      }
    ]
  },
  {
    "key": "heading",
    "title": "11. LOANS AND BORROWINGS",
    "variant": "subtitle",
    "align": "left"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "The Firm may raise loans from banks, financial institutions, or others for business purposes. Such borrowings shall be made only with the consent of both Partners, and both shall be equally liable."
      }
    ]
  },
  {
    "key": "heading",
    "title": "12. ADMISSION, RETIREMENT, OR DEATH OF PARTNER",
    "variant": "subtitle",
    "align": "left"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "bullet",
        "align": "justify",
        "indent": 0,
        "html": "No new Partner shall be admitted without written consent of both Partners."
      },
      {
        "kind": "bullet",
        "align": "justify",
        "indent": 0,
        "html": "<b>A Partner may retire after completion of five years, by giving three months’ written notice.</b>"
      },
      {
        "kind": "bullet",
        "align": "justify",
        "indent": 0,
        "html": "In the event of the death of a Partner, the surviving Partner may continue the business with the legal heir(s) of the deceased Partner, or may settle the share of the deceased."
      }
    ]
  },
  {
    "key": "heading",
    "title": "13. RESTRICTION ON TRANSFER OF SHARE",
    "variant": "subtitle",
    "align": "left"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "No Partner shall transfer, assign, or mortgage his/her share in the Firm without the written consent of the other Partner."
      }
    ]
  },
  {
    "key": "heading",
    "title": "14. GOODWILL",
    "variant": "subtitle",
    "align": "left"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "The goodwill of the Firm shall belong to the Firm. On dissolution, goodwill shall be valued and shared equally between the Partners."
      }
    ]
  },
  {
    "key": "heading",
    "title": "15. DISPUTE RESOLUTION",
    "variant": "subtitle",
    "align": "left"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "Any dispute between the Partners shall first be resolved amicably through mutual discussion. Failing which, the matter shall be referred to arbitration under the provisions of the Arbitration and Conciliation Act, 1996, and the decision of the arbitrator shall be final and binding."
      }
    ]
  },
  {
    "key": "heading",
    "title": "16. GOVERNING LAW",
    "variant": "subtitle",
    "align": "left"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "This Deed shall be governed by the provisions of the Indian Partnership Act, 1932, and other applicable laws in force."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "IN WITNESS WHEREOF"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "The Partners hereto have signed this Partnership Deed on the date, month, and year first above written."
      },
      {
        "kind": "p",
        "align": "left",
        "indent": 0,
        "html": "Partner 1"
      },
      {
        "kind": "p",
        "align": "left",
        "indent": 0,
        "html": "Signature: ____________________"
      },
      {
        "kind": "p",
        "align": "left",
        "indent": 0,
        "html": "Name: {{partner1_name}}"
      },
      {
        "kind": "p",
        "align": "left",
        "indent": 0,
        "html": "Partner 2"
      },
      {
        "kind": "p",
        "align": "left",
        "indent": 0,
        "html": "Signature: ____________________"
      },
      {
        "kind": "p",
        "align": "left",
        "indent": 0,
        "html": "Name: {{partner2_name}}"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "Witnesses:"
      },
      {
        "kind": "bullet",
        "align": "justify",
        "indent": 0,
        "html": "Name:"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "Address:"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "Signature:"
      },
      {
        "kind": "bullet",
        "align": "justify",
        "indent": 0,
        "html": "Name:"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "Address:"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "Signature:"
      }
    ]
  }
] as RawBlock[];
