/**
 * The LLP agreement — Section 23(4) of the LLP Act, 2008.
 *
 * GENERATED by scripts/build-doc-templates.mjs from the reference document.
 * Edit the reference and re-run the script rather than editing this file:
 * the clauses are a legal text, and hand-editing them here is how one goes
 * missing. The firm's own particulars are {{placeholders}}, declared as
 * fields on the document type in ../registry.ts.
 */
import type { RawBlock } from '../model';

export const LLP_AGREEMENT_BLOCKS: RawBlock[] = [
  {
    "key": "heading",
    "title": "LLP AGREEMENT",
    "variant": "title",
    "align": "center"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "center",
        "indent": 0,
        "html": "(As per Section 23(4) of LLP Act, 2008)"
      },
      {
        "kind": "p",
        "align": "center",
        "indent": 0,
        "html": "This Agreement of LLP made at {{place}} on this {{agreement_date}}."
      }
    ]
  },
  {
    "key": "heading",
    "title": "BETWEEN",
    "variant": "subtitle",
    "align": "center"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "1. {{partner1_name}}, {{partner1_details}} which expression shall, unless it be repugnant to the subject or context thereof, include their legal heirs, successors, nominees and permitted assignees and hereinafter called the FIRST PARTY."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "2. {{partner2_name}}, {{partner2_details}} which expression shall, unless it be repugnant to the subject or context thereof, include their legal heirs, successors, nominees and permitted assignees and hereinafter called the SECOND PARTY."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "(ALL THE FIRST and SECOND PARTY SHALL BE COLLECTIVELY REFERRED TO AS PARTNERS)"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "NOW the FIRST and SECOND Party are interested in forming a limited liability partnership under the limited liability partnership Act 2008 and that they intends to write down the terms and conditions of the said formation and"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "IT IS HEREBY AGREED BY AND BETWEEN THE PARTIES HERETO AS FOLLOWS:"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "1. A limited liability partnership shall be carried on in the name and style of {{llp_name}} and hereinafter called as LLP."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "2. The LLP shall have its registered office at {{registered_office}} and/or at such other place or places, as shall be agreed to by the majority of the partners from time to time."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "3. The Contribution of the LLP shall be Rs. {{contribution}} which shall be contributed by the partners in the following proportions:"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "FIRST Party 50.00% i.e. 25,000 Only."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "SECOND Party 50.00% i.e. 25,000 Only."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "Further Contribution if any required by the LLP shall be brought in by the partners in their profit-sharing ratio."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "5. The LLP shall have a common seal to be affixed on documents as defined by partners under the signature of any of the Designated Partners."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "6. All the Partners of the LLP are entitled to share profit and losses in the ratio of their capital contribution."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "7. The business of the LLP shall be: to carry on the business activity of {{business_activity}}."
      }
    ]
  },
  {
    "key": "heading",
    "title": "Admission of New Partner",
    "variant": "subtitle",
    "align": "center"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "8. No person may be introduced as a new partner without the consent of all the existing partners. Such incoming partner shall give his/her prior consent to act as Partner of the LLP."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "9. The contribution of the partner may be tangible, intangible, moveable or immoveable property and the incoming partner shall bring minimum contribution of Rs. 50,000."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "10. The profit-sharing ratio of the incoming partner will be in proportion to his/her contribution towards the LLP."
      }
    ]
  },
  {
    "key": "heading",
    "title": "Rights of Partner",
    "variant": "subtitle",
    "align": "center"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "11. All the partners hereto shall have the rights, title and interest in all the assets and properties in the said LLP in the proportion of their contribution."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "12. Every partner has a right to have access to and to inspect and copy any books of the LLP."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "13. Each of the parties hereto shall be entitled to carry on their own, separate and independent business as hitherto they might be doing or they may hereafter do as they deem fit and proper and other partners and the LLP shall have no objection thereto provided that the said partner has intimated the said fact to the LLP before the start of the independent business and moreover he/she shall not use the name of the LLP to carry on the said business."
      },
      {
        "kind": "p",
        "align": "left",
        "indent": 0,
        "html": "14. LLP shall have perpetual succession. Death, retirement or insolvency of any partner shall not dissolve the LLP."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "15. On retirement of a partner, the retiring partner shall be entitled to full payment in respect of all his/her rights, title and interest in the partnership. However, insolvency of a partner his or her rights, title and interest in the LLP shall come to an end."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "16. Upon the death of any of the partners herein any one of his or her heirs will be admitted as a partner of the LLP in the place of such deceased partner. The heirs, executors and administrators of such deceased partners shall be entitled to and shall be paid the full payment in respect of the right, title and interest of such deceased partner."
      }
    ]
  },
  {
    "key": "heading",
    "title": "Duties of Partners",
    "variant": "subtitle",
    "align": "center"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "17. Every partner shall account to the LLP for any benefit derived by him without the consent of the LLP from any transaction concerning the LLP, or from any use by him of the property, name or any business connection of the LLP."
      }
    ]
  },
  {
    "key": "signature",
    "variant": "upload",
    "columns": 2,
    "people": [
      {
        "name": "",
        "role": "",
        "din": "",
        "note": ""
      },
      {
        "name": "",
        "role": "",
        "din": "",
        "note": ""
      }
    ]
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "18. Every partner shall indemnify the LLP and the other existing partner for any loss caused to it by his/her fraud in the conduct of the business of the LLP."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "19. Each partner shall render true accounts and full information of all things affecting the LLP to any partner or his/her legal representatives."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "20. In case any of the Partners of the LLP desires to transfer or assign his/her interest or shares in the LLP he has to offer the same to the remaining partners by giving 15 days’ notice. In the absence of any communication by the remaining partners the concerned partner can transfer or assign his/her share in the market."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "21. No partner shall without the written consent of the LLP :--"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "1. Employ any money, goods or effects of the LLP or pledge the credit thereof except in the ordinary course of business and upon the account or for the benefit of the LLP."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "2. Lend money or give credit on behalf of the LLP or to have any dealings with any persons, company or firm whom the other partner previously in writing have forbidden it to trust or deal with. Any loss incurred through any breach of provisions shall be made good with the LLP by the partner incurring the same."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "3. Enter into any bond or becomes surety or security with or for any person or do knowingly cause or suffer to be done anything whereby the LLP property or any part thereof may be seized."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "4. Assign, mortgage or charge his or her share in the LLP or any asset or property thereof or make any other person a partner therein."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "5. Compromise or compound or (except upon payment in full) release or discharge any debt due to the LLP except upon the written consent given by the other partner."
      }
    ]
  },
  {
    "key": "heading",
    "title": "Meetings",
    "variant": "subtitle",
    "align": "center"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "22. All the matters related to the LLP shall be decided by a resolution passed by a majority in number of the partners, and for this purpose, each partner shall have one vote."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "23. The meeting of the Partners may be called by sending 15 days prior notice to all the partners at their residential address or by mail at the email ids provided by the individual partners. In case any partner is a foreign resident the meeting may be conducted by serving 15 days prior notice through email. Provided the meeting be called at shorter notice, if majority of the partners agrees in writing to the same either before or after the meeting."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "24. The meeting of partners shall ordinarily be held at the registered office of the LLP or at any other place as per the convenience of partners."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "25. With the written consent of all the partners, a meeting of the partners may be conducted through teleconferencing."
      },
      {
        "kind": "p",
        "align": "left",
        "indent": 0,
        "html": "26. Every LLP shall ensure that decisions taken by it are recorded in the minutes within thirty days of taking such decisions and are kept and maintained at the registered office of the LLP."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "27. Each partner shall:-"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "1. Punctually pay and discharge the separate debts and engagement and indemnify the other partners and the LLP assets against the same and all proceedings, costs, claims and demands in respect thereof."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "2. Each of the partners shall give time and attention as may be required for the fulfilment of the objectives of the LLP business and they all shall be the working partners."
      }
    ]
  },
  {
    "key": "heading",
    "title": "Duties of Designated Partner",
    "variant": "subtitle",
    "align": "center"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "28. The FIRST Party and SECOND Party shall act as the Designated Partner of the LLP in terms of the requirement of the LLP Act, 2008."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "29. The Designated Partners shall be responsible for doing all acts, matters and things as are required to be done by the LLP in respect of compliance of the provisions of this Act including filing of any document, return, statement and the like report pursuant to the provisions of LLP Act, 2008."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "30. The Designated Partners shall be responsible for the doing of all acts arising out of this agreement."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "31. The LLP shall pay such remuneration to the Designated Partner as may be decided by the majority of the Partners, for rendering his/her services as such."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "32. The LLP shall indemnify and defend its partners and other officers from and against any and all liability in connection with claims, actions and proceedings, judgment, loss or settlement thereof, whether civil or criminal, arising out of or resulting from their respective performances as partners and officers of the LLP except for the gross negligence or willful misconduct of the partner or officer seeking indemnification."
      }
    ]
  },
  {
    "key": "heading",
    "title": "Cessation of Existing Partners",
    "variant": "subtitle",
    "align": "center"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "33. Partner may cease to be partner of the LLP by giving a notice in writing of not less than thirty days to the other partners of his/her intention to resign as partner."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "34. No majority of Partners can expel any partner except in the situation where any partner has been found guilty of carrying of activity/business of LLP with fraudulent purpose."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "35. The LLP can be wounded up with the consent of all the partners subject to the provisions of LLP Act 2008."
      }
    ]
  },
  {
    "key": "heading",
    "title": "Death or voluntary retirement of Partner",
    "variant": "subtitle",
    "align": "center"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "36. If any Partner shall die or have voluntarily retired, a statement of account shall be taken and made out of his share of the capital and effects of the LLP and of all unpaid interest and profits due to him up to the time of his demise or retirement and be paid at the earliest as may be decided by the"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "Designated Partners of the LLP, subject to required adjustments between his capital account and income account transactions and transfers made till the date of death or retirement, as the case may be, and balances struck as certified by the Auditor for the time being of the LLP. The said statement of account shall include the Partner's share of profit and loss for the period from the beginning of the financial year in which his death or retirement occurs until the end of the calendar month in which the event takes place."
      }
    ]
  },
  {
    "key": "heading",
    "title": "Goodwill",
    "variant": "subtitle",
    "align": "center"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "37. A valuation of the assets, effects and of the goodwill including the Partnership name shall be made at three times the average net yearly profits of the preceding five years or the commencement of the LLP, whichever is less, for the purpose to determine the amount due to such a Partner who has exited, and the payment shall be met by the Partners remaining with the LLP in proportion to their respective capital contribution on the date of his exit within six (6) calendar months from the date of exit, any delay beyond attracting interest at 12 (twelve)per cent per annum from the date of expiry of the said six months till the actual date of payment. On such a payment being made the share of the Partner exited in the goodwill shall stand vested in the remaining Partners of the LLP."
      }
    ]
  },
  {
    "key": "heading",
    "title": "Extent of Liability",
    "variant": "subtitle",
    "align": "center"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "38. LLP is not bound by anything done by a partner in dealing with a person if:-"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "1. The partner in fact has no authority to act for the LLP in doing a particular act; and"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "2. The person knows that he/she has no authority or does not know or believe him to be a partner of"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "the LLP."
      }
    ]
  },
  {
    "key": "heading",
    "title": "Banking & Borrowing powers",
    "variant": "subtitle",
    "align": "center"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "39. The Designated partners can open bank accounts for the LLP with any Banks / Financial Institutions."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "40. It is expressly agreed that the bank account of the LLP shall be operated by either any one or jointly, as mutually agreed among the parties"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "41. It is also expressly agreed that the LLP can borrow from any banks / financial institutions for the LLP."
      }
    ]
  },
  {
    "key": "heading",
    "title": "Miscellaneous Provisions",
    "variant": "subtitle",
    "align": "center"
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "42. The LLP shall indemnify each partner in respect of payments made and personal liabilities incurred by him/her:"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "1. in the ordinary and proper conduct of the business of the LLP; OR"
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "2. in or about anything necessarily done for the preservation of the business or property of the LLP."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "43. The books of accounts of the firm shall be kept at the registered office of the LLP for the reference of all the partners."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "44. The accounting year of the LLP shall be from 1st April of every year to 31st March of subsequent year. The first accounting year shall be from the date of commencement of this LLP till 31st March of the subsequent year."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "45. All disputes between the partners or between the Partner and the LLP arising out of the LLP agreement which cannot be resolved in terms of this agreement shall be referred for arbitration as per the provisions of the Arbitration and Conciliation Act, 1996."
      },
      {
        "kind": "p",
        "align": "justify",
        "indent": 0,
        "html": "IN WITNESS WHEREOF the parties have set their respective hands the day and year first above written."
      }
    ]
  },
  {
    "key": "paragraph",
    "lines": [
      {
        "kind": "p",
        "align": "left",
        "indent": 0,
        "html": "<b>Signed and delivered by:</b>"
      }
    ]
  },
  {
    "key": "signature",
    "columns": 2,
    "people": [
      {
        "name": "{{partner1_name}}",
        "role": "(Designated Partner) ({{partner1_din}})",
        "din": "",
        "note": ""
      },
      {
        "name": "{{partner2_name}}",
        "role": "(Designated Partner) ({{partner2_din}})",
        "din": "",
        "note": ""
      }
    ]
  },
  {
    "key": "witness",
    "people": [
      {
        "name": "",
        "role": "",
        "din": "a)",
        "note": "Witness:"
      },
      {
        "name": "",
        "role": "",
        "din": "b)",
        "note": "Witness:"
      }
    ]
  }
] as RawBlock[];
