BEGIN;
ALTER TABLE "TallyAttendanceRecord" RENAME TO "BookkeepingAttendanceRecord";
ALTER TABLE "TallyBackup" RENAME TO "BookkeepingBackup";
ALTER TABLE "TallyBankReconciliation" RENAME TO "BookkeepingBankReconciliation";
ALTER TABLE "TallyBankStatementLine" RENAME TO "BookkeepingBankStatementLine";
ALTER TABLE "TallyBillAllocation" RENAME TO "BookkeepingBillAllocation";
ALTER TABLE "TallyCompany" RENAME TO "BookkeepingCompany";
ALTER TABLE "TallyEmployee" RENAME TO "BookkeepingEmployee";
ALTER TABLE "TallyFinancialYear" RENAME TO "BookkeepingFinancialYear";
ALTER TABLE "TallyGodown" RENAME TO "BookkeepingGodown";
ALTER TABLE "TallyGroup" RENAME TO "BookkeepingGroup";
ALTER TABLE "TallyLedger" RENAME TO "BookkeepingLedger";
ALTER TABLE "TallyPayHead" RENAME TO "BookkeepingPayHead";
ALTER TABLE "TallyPayrollLine" RENAME TO "BookkeepingPayrollLine";
ALTER TABLE "TallyPayrollRun" RENAME TO "BookkeepingPayrollRun";
ALTER TABLE "TallySalaryStructureLine" RENAME TO "BookkeepingSalaryStructureLine";
ALTER TABLE "TallySetting" RENAME TO "BookkeepingSetting";
ALTER TABLE "TallyStockBatch" RENAME TO "BookkeepingStockBatch";
ALTER TABLE "TallyStockCategory" RENAME TO "BookkeepingStockCategory";
ALTER TABLE "TallyStockGroup" RENAME TO "BookkeepingStockGroup";
ALTER TABLE "TallyStockItem" RENAME TO "BookkeepingStockItem";
ALTER TABLE "TallyStockOpening" RENAME TO "BookkeepingStockOpening";
ALTER TABLE "TallyTaxRate" RENAME TO "BookkeepingTaxRate";
ALTER TABLE "TallyUnit" RENAME TO "BookkeepingUnit";
ALTER TABLE "TallyVoucher" RENAME TO "BookkeepingVoucher";
ALTER TABLE "TallyVoucherEntry" RENAME TO "BookkeepingVoucherEntry";
ALTER TABLE "TallyVoucherItem" RENAME TO "BookkeepingVoucherItem";
ALTER TABLE "TallyVoucherRevision" RENAME TO "BookkeepingVoucherRevision";
ALTER TABLE "TallyVoucherType" RENAME TO "BookkeepingVoucherType";
ALTER TABLE "BookkeepingCompany" RENAME CONSTRAINT "TallyCompany_organisationId_fkey" TO "BookkeepingCompany_organisationId_fkey";
ALTER TABLE "BookkeepingCompany" RENAME CONSTRAINT "TallyCompany_pkey" TO "BookkeepingCompany_pkey";
ALTER TABLE "BookkeepingFinancialYear" RENAME CONSTRAINT "TallyFinancialYear_pkey" TO "BookkeepingFinancialYear_pkey";
ALTER TABLE "BookkeepingFinancialYear" RENAME CONSTRAINT "TallyFinancialYear_tallyCompanyId_fkey" TO "BookkeepingFinancialYear_tallyCompanyId_fkey";
ALTER TABLE "BookkeepingGroup" RENAME CONSTRAINT "TallyGroup_parentGroupId_fkey" TO "BookkeepingGroup_parentGroupId_fkey";
ALTER TABLE "BookkeepingGroup" RENAME CONSTRAINT "TallyGroup_pkey" TO "BookkeepingGroup_pkey";
ALTER TABLE "BookkeepingGroup" RENAME CONSTRAINT "TallyGroup_tallyCompanyId_fkey" TO "BookkeepingGroup_tallyCompanyId_fkey";
ALTER TABLE "BookkeepingLedger" RENAME CONSTRAINT "TallyLedger_groupId_fkey" TO "BookkeepingLedger_groupId_fkey";
ALTER TABLE "BookkeepingLedger" RENAME CONSTRAINT "TallyLedger_openingBalanceAsOfFyId_fkey" TO "BookkeepingLedger_openingBalanceAsOfFyId_fkey";
ALTER TABLE "BookkeepingLedger" RENAME CONSTRAINT "TallyLedger_pkey" TO "BookkeepingLedger_pkey";
ALTER TABLE "BookkeepingLedger" RENAME CONSTRAINT "TallyLedger_tallyCompanyId_fkey" TO "BookkeepingLedger_tallyCompanyId_fkey";
ALTER TABLE "BookkeepingVoucherType" RENAME CONSTRAINT "TallyVoucherType_pkey" TO "BookkeepingVoucherType_pkey";
ALTER TABLE "BookkeepingVoucherType" RENAME CONSTRAINT "TallyVoucherType_tallyCompanyId_fkey" TO "BookkeepingVoucherType_tallyCompanyId_fkey";
ALTER TABLE "BookkeepingVoucher" RENAME CONSTRAINT "TallyVoucher_financialYearId_fkey" TO "BookkeepingVoucher_financialYearId_fkey";
ALTER TABLE "BookkeepingVoucher" RENAME CONSTRAINT "TallyVoucher_partyLedgerId_fkey" TO "BookkeepingVoucher_partyLedgerId_fkey";
ALTER TABLE "BookkeepingVoucher" RENAME CONSTRAINT "TallyVoucher_pkey" TO "BookkeepingVoucher_pkey";
ALTER TABLE "BookkeepingVoucher" RENAME CONSTRAINT "TallyVoucher_tallyCompanyId_fkey" TO "BookkeepingVoucher_tallyCompanyId_fkey";
ALTER TABLE "BookkeepingVoucher" RENAME CONSTRAINT "TallyVoucher_voucherTypeId_fkey" TO "BookkeepingVoucher_voucherTypeId_fkey";
ALTER TABLE "BookkeepingVoucherEntry" RENAME CONSTRAINT "TallyVoucherEntry_bankStatementLineId_fkey" TO "BookkeepingVoucherEntry_bankStatementLineId_fkey";
ALTER TABLE "BookkeepingVoucherEntry" RENAME CONSTRAINT "TallyVoucherEntry_ledgerId_fkey" TO "BookkeepingVoucherEntry_ledgerId_fkey";
ALTER TABLE "BookkeepingVoucherEntry" RENAME CONSTRAINT "TallyVoucherEntry_pkey" TO "BookkeepingVoucherEntry_pkey";
ALTER TABLE "BookkeepingVoucherEntry" RENAME CONSTRAINT "TallyVoucherEntry_voucherId_fkey" TO "BookkeepingVoucherEntry_voucherId_fkey";
ALTER TABLE "BookkeepingBillAllocation" RENAME CONSTRAINT "TallyBillAllocation_ledgerId_fkey" TO "BookkeepingBillAllocation_ledgerId_fkey";
ALTER TABLE "BookkeepingBillAllocation" RENAME CONSTRAINT "TallyBillAllocation_pkey" TO "BookkeepingBillAllocation_pkey";
ALTER TABLE "BookkeepingBillAllocation" RENAME CONSTRAINT "TallyBillAllocation_voucherEntryId_fkey" TO "BookkeepingBillAllocation_voucherEntryId_fkey";
ALTER TABLE "BookkeepingBillAllocation" RENAME CONSTRAINT "TallyBillAllocation_voucherId_fkey" TO "BookkeepingBillAllocation_voucherId_fkey";
ALTER TABLE "BookkeepingVoucherItem" RENAME CONSTRAINT "TallyVoucherItem_batchId_fkey" TO "BookkeepingVoucherItem_batchId_fkey";
ALTER TABLE "BookkeepingVoucherItem" RENAME CONSTRAINT "TallyVoucherItem_godownId_fkey" TO "BookkeepingVoucherItem_godownId_fkey";
ALTER TABLE "BookkeepingVoucherItem" RENAME CONSTRAINT "TallyVoucherItem_pkey" TO "BookkeepingVoucherItem_pkey";
ALTER TABLE "BookkeepingVoucherItem" RENAME CONSTRAINT "TallyVoucherItem_stockItemId_fkey" TO "BookkeepingVoucherItem_stockItemId_fkey";
ALTER TABLE "BookkeepingVoucherItem" RENAME CONSTRAINT "TallyVoucherItem_voucherId_fkey" TO "BookkeepingVoucherItem_voucherId_fkey";
ALTER TABLE "BookkeepingVoucherRevision" RENAME CONSTRAINT "TallyVoucherRevision_pkey" TO "BookkeepingVoucherRevision_pkey";
ALTER TABLE "BookkeepingVoucherRevision" RENAME CONSTRAINT "TallyVoucherRevision_voucherId_fkey" TO "BookkeepingVoucherRevision_voucherId_fkey";
ALTER TABLE "BookkeepingStockGroup" RENAME CONSTRAINT "TallyStockGroup_parentId_fkey" TO "BookkeepingStockGroup_parentId_fkey";
ALTER TABLE "BookkeepingStockGroup" RENAME CONSTRAINT "TallyStockGroup_pkey" TO "BookkeepingStockGroup_pkey";
ALTER TABLE "BookkeepingStockGroup" RENAME CONSTRAINT "TallyStockGroup_tallyCompanyId_fkey" TO "BookkeepingStockGroup_tallyCompanyId_fkey";
ALTER TABLE "BookkeepingStockCategory" RENAME CONSTRAINT "TallyStockCategory_pkey" TO "BookkeepingStockCategory_pkey";
ALTER TABLE "BookkeepingStockCategory" RENAME CONSTRAINT "TallyStockCategory_tallyCompanyId_fkey" TO "BookkeepingStockCategory_tallyCompanyId_fkey";
ALTER TABLE "BookkeepingUnit" RENAME CONSTRAINT "TallyUnit_pkey" TO "BookkeepingUnit_pkey";
ALTER TABLE "BookkeepingUnit" RENAME CONSTRAINT "TallyUnit_tallyCompanyId_fkey" TO "BookkeepingUnit_tallyCompanyId_fkey";
ALTER TABLE "BookkeepingGodown" RENAME CONSTRAINT "TallyGodown_parentId_fkey" TO "BookkeepingGodown_parentId_fkey";
ALTER TABLE "BookkeepingGodown" RENAME CONSTRAINT "TallyGodown_pkey" TO "BookkeepingGodown_pkey";
ALTER TABLE "BookkeepingGodown" RENAME CONSTRAINT "TallyGodown_tallyCompanyId_fkey" TO "BookkeepingGodown_tallyCompanyId_fkey";
ALTER TABLE "BookkeepingStockItem" RENAME CONSTRAINT "TallyStockItem_categoryId_fkey" TO "BookkeepingStockItem_categoryId_fkey";
ALTER TABLE "BookkeepingStockItem" RENAME CONSTRAINT "TallyStockItem_pkey" TO "BookkeepingStockItem_pkey";
ALTER TABLE "BookkeepingStockItem" RENAME CONSTRAINT "TallyStockItem_stockGroupId_fkey" TO "BookkeepingStockItem_stockGroupId_fkey";
ALTER TABLE "BookkeepingStockItem" RENAME CONSTRAINT "TallyStockItem_tallyCompanyId_fkey" TO "BookkeepingStockItem_tallyCompanyId_fkey";
ALTER TABLE "BookkeepingStockItem" RENAME CONSTRAINT "TallyStockItem_unitId_fkey" TO "BookkeepingStockItem_unitId_fkey";
ALTER TABLE "BookkeepingStockOpening" RENAME CONSTRAINT "TallyStockOpening_batchId_fkey" TO "BookkeepingStockOpening_batchId_fkey";
ALTER TABLE "BookkeepingStockOpening" RENAME CONSTRAINT "TallyStockOpening_godownId_fkey" TO "BookkeepingStockOpening_godownId_fkey";
ALTER TABLE "BookkeepingStockOpening" RENAME CONSTRAINT "TallyStockOpening_pkey" TO "BookkeepingStockOpening_pkey";
ALTER TABLE "BookkeepingStockOpening" RENAME CONSTRAINT "TallyStockOpening_stockItemId_fkey" TO "BookkeepingStockOpening_stockItemId_fkey";
ALTER TABLE "BookkeepingStockBatch" RENAME CONSTRAINT "TallyStockBatch_pkey" TO "BookkeepingStockBatch_pkey";
ALTER TABLE "BookkeepingStockBatch" RENAME CONSTRAINT "TallyStockBatch_stockItemId_fkey" TO "BookkeepingStockBatch_stockItemId_fkey";
ALTER TABLE "BookkeepingBankStatementLine" RENAME CONSTRAINT "TallyBankStatementLine_bankLedgerId_fkey" TO "BookkeepingBankStatementLine_bankLedgerId_fkey";
ALTER TABLE "BookkeepingBankStatementLine" RENAME CONSTRAINT "TallyBankStatementLine_pkey" TO "BookkeepingBankStatementLine_pkey";
ALTER TABLE "BookkeepingBankStatementLine" RENAME CONSTRAINT "TallyBankStatementLine_tallyCompanyId_fkey" TO "BookkeepingBankStatementLine_tallyCompanyId_fkey";
ALTER TABLE "BookkeepingBankReconciliation" RENAME CONSTRAINT "TallyBankReconciliation_bankLedgerId_fkey" TO "BookkeepingBankReconciliation_bankLedgerId_fkey";
ALTER TABLE "BookkeepingBankReconciliation" RENAME CONSTRAINT "TallyBankReconciliation_pkey" TO "BookkeepingBankReconciliation_pkey";
ALTER TABLE "BookkeepingBankReconciliation" RENAME CONSTRAINT "TallyBankReconciliation_tallyCompanyId_fkey" TO "BookkeepingBankReconciliation_tallyCompanyId_fkey";
ALTER TABLE "BookkeepingTaxRate" RENAME CONSTRAINT "TallyTaxRate_pkey" TO "BookkeepingTaxRate_pkey";
ALTER TABLE "BookkeepingTaxRate" RENAME CONSTRAINT "TallyTaxRate_tallyCompanyId_fkey" TO "BookkeepingTaxRate_tallyCompanyId_fkey";
ALTER TABLE "BookkeepingSetting" RENAME CONSTRAINT "TallySetting_pkey" TO "BookkeepingSetting_pkey";
ALTER TABLE "BookkeepingSetting" RENAME CONSTRAINT "TallySetting_tallyCompanyId_fkey" TO "BookkeepingSetting_tallyCompanyId_fkey";
ALTER TABLE "BookkeepingEmployee" RENAME CONSTRAINT "TallyEmployee_pkey" TO "BookkeepingEmployee_pkey";
ALTER TABLE "BookkeepingEmployee" RENAME CONSTRAINT "TallyEmployee_tallyCompanyId_fkey" TO "BookkeepingEmployee_tallyCompanyId_fkey";
ALTER TABLE "BookkeepingPayHead" RENAME CONSTRAINT "TallyPayHead_ledgerId_fkey" TO "BookkeepingPayHead_ledgerId_fkey";
ALTER TABLE "BookkeepingPayHead" RENAME CONSTRAINT "TallyPayHead_pkey" TO "BookkeepingPayHead_pkey";
ALTER TABLE "BookkeepingPayHead" RENAME CONSTRAINT "TallyPayHead_tallyCompanyId_fkey" TO "BookkeepingPayHead_tallyCompanyId_fkey";
ALTER TABLE "BookkeepingSalaryStructureLine" RENAME CONSTRAINT "TallySalaryStructureLine_employeeId_fkey" TO "BookkeepingSalaryStructureLine_employeeId_fkey";
ALTER TABLE "BookkeepingSalaryStructureLine" RENAME CONSTRAINT "TallySalaryStructureLine_payHeadId_fkey" TO "BookkeepingSalaryStructureLine_payHeadId_fkey";
ALTER TABLE "BookkeepingSalaryStructureLine" RENAME CONSTRAINT "TallySalaryStructureLine_pkey" TO "BookkeepingSalaryStructureLine_pkey";
ALTER TABLE "BookkeepingAttendanceRecord" RENAME CONSTRAINT "TallyAttendanceRecord_employeeId_fkey" TO "BookkeepingAttendanceRecord_employeeId_fkey";
ALTER TABLE "BookkeepingAttendanceRecord" RENAME CONSTRAINT "TallyAttendanceRecord_pkey" TO "BookkeepingAttendanceRecord_pkey";
ALTER TABLE "BookkeepingPayrollRun" RENAME CONSTRAINT "TallyPayrollRun_pkey" TO "BookkeepingPayrollRun_pkey";
ALTER TABLE "BookkeepingPayrollRun" RENAME CONSTRAINT "TallyPayrollRun_tallyCompanyId_fkey" TO "BookkeepingPayrollRun_tallyCompanyId_fkey";
ALTER TABLE "BookkeepingPayrollLine" RENAME CONSTRAINT "TallyPayrollLine_employeeId_fkey" TO "BookkeepingPayrollLine_employeeId_fkey";
ALTER TABLE "BookkeepingPayrollLine" RENAME CONSTRAINT "TallyPayrollLine_payHeadId_fkey" TO "BookkeepingPayrollLine_payHeadId_fkey";
ALTER TABLE "BookkeepingPayrollLine" RENAME CONSTRAINT "TallyPayrollLine_payrollRunId_fkey" TO "BookkeepingPayrollLine_payrollRunId_fkey";
ALTER TABLE "BookkeepingPayrollLine" RENAME CONSTRAINT "TallyPayrollLine_pkey" TO "BookkeepingPayrollLine_pkey";
ALTER TABLE "BookkeepingBackup" RENAME CONSTRAINT "TallyBackup_pkey" TO "BookkeepingBackup_pkey";
ALTER TABLE "BookkeepingBackup" RENAME CONSTRAINT "TallyBackup_tallyCompanyId_fkey" TO "BookkeepingBackup_tallyCompanyId_fkey";
ALTER INDEX "TallyCompany_organisationId_idx" RENAME TO "BookkeepingCompany_organisationId_idx";
ALTER INDEX "TallyCompany_organisationId_name_key" RENAME TO "BookkeepingCompany_organisationId_name_key";
ALTER INDEX "TallyFinancialYear_tallyCompanyId_idx" RENAME TO "BookkeepingFinancialYear_tallyCompanyId_idx";
ALTER INDEX "TallyFinancialYear_tallyCompanyId_label_key" RENAME TO "BookkeepingFinancialYear_tallyCompanyId_label_key";
ALTER INDEX "TallyGroup_tallyCompanyId_idx" RENAME TO "BookkeepingGroup_tallyCompanyId_idx";
ALTER INDEX "TallyGroup_parentGroupId_idx" RENAME TO "BookkeepingGroup_parentGroupId_idx";
ALTER INDEX "TallyGroup_tallyCompanyId_name_key" RENAME TO "BookkeepingGroup_tallyCompanyId_name_key";
ALTER INDEX "TallyLedger_tallyCompanyId_idx" RENAME TO "BookkeepingLedger_tallyCompanyId_idx";
ALTER INDEX "TallyLedger_groupId_idx" RENAME TO "BookkeepingLedger_groupId_idx";
ALTER INDEX "TallyLedger_tallyCompanyId_name_key" RENAME TO "BookkeepingLedger_tallyCompanyId_name_key";
ALTER INDEX "TallyVoucherType_tallyCompanyId_code_idx" RENAME TO "BookkeepingVoucherType_tallyCompanyId_code_idx";
ALTER INDEX "TallyVoucherType_tallyCompanyId_name_key" RENAME TO "BookkeepingVoucherType_tallyCompanyId_name_key";
ALTER INDEX "TallyVoucher_tallyCompanyId_date_idx" RENAME TO "BookkeepingVoucher_tallyCompanyId_date_idx";
ALTER INDEX "TallyVoucher_tallyCompanyId_voucherTypeCode_date_idx" RENAME TO "BookkeepingVoucher_tallyCompanyId_voucherTypeCode_date_idx";
ALTER INDEX "TallyVoucher_tallyCompanyId_partyLedgerId_idx" RENAME TO "BookkeepingVoucher_tallyCompanyId_partyLedgerId_idx";
ALTER INDEX "TallyVoucher_financialYearId_idx" RENAME TO "BookkeepingVoucher_financialYearId_idx";
ALTER INDEX "TallyVoucher_tallyCompanyId_voucherTypeId_voucherNumber_key" RENAME TO "BookkeepingVoucher_tallyCompanyId_voucherTypeId_voucherNumber_key";
ALTER INDEX "TallyVoucherEntry_bankStatementLineId_key" RENAME TO "BookkeepingVoucherEntry_bankStatementLineId_key";
ALTER INDEX "TallyVoucherEntry_tallyCompanyId_ledgerId_idx" RENAME TO "BookkeepingVoucherEntry_tallyCompanyId_ledgerId_idx";
ALTER INDEX "TallyVoucherEntry_voucherId_idx" RENAME TO "BookkeepingVoucherEntry_voucherId_idx";
ALTER INDEX "TallyVoucherEntry_ledgerId_idx" RENAME TO "BookkeepingVoucherEntry_ledgerId_idx";
ALTER INDEX "TallyBillAllocation_tallyCompanyId_ledgerId_billRef_idx" RENAME TO "BookkeepingBillAllocation_tallyCompanyId_ledgerId_billRef_idx";
ALTER INDEX "TallyBillAllocation_voucherId_idx" RENAME TO "BookkeepingBillAllocation_voucherId_idx";
ALTER INDEX "TallyVoucherItem_tallyCompanyId_stockItemId_idx" RENAME TO "BookkeepingVoucherItem_tallyCompanyId_stockItemId_idx";
ALTER INDEX "TallyVoucherItem_voucherId_idx" RENAME TO "BookkeepingVoucherItem_voucherId_idx";
ALTER INDEX "TallyVoucherItem_godownId_idx" RENAME TO "BookkeepingVoucherItem_godownId_idx";
ALTER INDEX "TallyVoucherRevision_tallyCompanyId_createdAt_idx" RENAME TO "BookkeepingVoucherRevision_tallyCompanyId_createdAt_idx";
ALTER INDEX "TallyVoucherRevision_voucherId_idx" RENAME TO "BookkeepingVoucherRevision_voucherId_idx";
ALTER INDEX "TallyStockGroup_tallyCompanyId_idx" RENAME TO "BookkeepingStockGroup_tallyCompanyId_idx";
ALTER INDEX "TallyStockGroup_tallyCompanyId_name_key" RENAME TO "BookkeepingStockGroup_tallyCompanyId_name_key";
ALTER INDEX "TallyStockCategory_tallyCompanyId_name_key" RENAME TO "BookkeepingStockCategory_tallyCompanyId_name_key";
ALTER INDEX "TallyUnit_tallyCompanyId_name_key" RENAME TO "BookkeepingUnit_tallyCompanyId_name_key";
ALTER INDEX "TallyGodown_tallyCompanyId_name_key" RENAME TO "BookkeepingGodown_tallyCompanyId_name_key";
ALTER INDEX "TallyStockItem_tallyCompanyId_idx" RENAME TO "BookkeepingStockItem_tallyCompanyId_idx";
ALTER INDEX "TallyStockItem_tallyCompanyId_name_key" RENAME TO "BookkeepingStockItem_tallyCompanyId_name_key";
ALTER INDEX "TallyStockOpening_tallyCompanyId_stockItemId_idx" RENAME TO "BookkeepingStockOpening_tallyCompanyId_stockItemId_idx";
ALTER INDEX "TallyStockBatch_tallyCompanyId_idx" RENAME TO "BookkeepingStockBatch_tallyCompanyId_idx";
ALTER INDEX "TallyStockBatch_stockItemId_name_key" RENAME TO "BookkeepingStockBatch_stockItemId_name_key";
ALTER INDEX "TallyBankStatementLine_tallyCompanyId_bankLedgerId_date_idx" RENAME TO "BookkeepingBankStatementLine_tallyCompanyId_bankLedgerId_date_idx";
ALTER INDEX "TallyBankReconciliation_tallyCompanyId_bankLedgerId_stateme_idx" RENAME TO "BookkeepingBankReconciliation_tallyCompanyId_bankLedgerId_stateme_idx";
ALTER INDEX "TallyTaxRate_tallyCompanyId_taxType_idx" RENAME TO "BookkeepingTaxRate_tallyCompanyId_taxType_idx";
ALTER INDEX "TallyTaxRate_tallyCompanyId_taxType_name_key" RENAME TO "BookkeepingTaxRate_tallyCompanyId_taxType_name_key";
ALTER INDEX "TallySetting_tallyCompanyId_key_key" RENAME TO "BookkeepingSetting_tallyCompanyId_key_key";
ALTER INDEX "TallyEmployee_tallyCompanyId_idx" RENAME TO "BookkeepingEmployee_tallyCompanyId_idx";
ALTER INDEX "TallyEmployee_tallyCompanyId_name_key" RENAME TO "BookkeepingEmployee_tallyCompanyId_name_key";
ALTER INDEX "TallyPayHead_tallyCompanyId_name_key" RENAME TO "BookkeepingPayHead_tallyCompanyId_name_key";
ALTER INDEX "TallySalaryStructureLine_tallyCompanyId_idx" RENAME TO "BookkeepingSalaryStructureLine_tallyCompanyId_idx";
ALTER INDEX "TallySalaryStructureLine_employeeId_payHeadId_key" RENAME TO "BookkeepingSalaryStructureLine_employeeId_payHeadId_key";
ALTER INDEX "TallyAttendanceRecord_tallyCompanyId_period_idx" RENAME TO "BookkeepingAttendanceRecord_tallyCompanyId_period_idx";
ALTER INDEX "TallyAttendanceRecord_employeeId_period_key" RENAME TO "BookkeepingAttendanceRecord_employeeId_period_key";
ALTER INDEX "TallyPayrollRun_tallyCompanyId_period_key" RENAME TO "BookkeepingPayrollRun_tallyCompanyId_period_key";
ALTER INDEX "TallyPayrollLine_payrollRunId_idx" RENAME TO "BookkeepingPayrollLine_payrollRunId_idx";
ALTER INDEX "TallyPayrollLine_tallyCompanyId_employeeId_idx" RENAME TO "BookkeepingPayrollLine_tallyCompanyId_employeeId_idx";
ALTER INDEX "TallyBackup_tallyCompanyId_createdAt_idx" RENAME TO "BookkeepingBackup_tallyCompanyId_createdAt_idx";
COMMIT;
-- Follow-up cleanup applied after safe-push recreated empty Tally tables; drop them and repair three long index names Postgres truncated.
DROP TABLE IF EXISTS "TallyCompany" CASCADE;
DROP TABLE IF EXISTS "TallyFinancialYear" CASCADE;
DROP TABLE IF EXISTS "TallyGroup" CASCADE;
DROP TABLE IF EXISTS "TallyLedger" CASCADE;
DROP TABLE IF EXISTS "TallyVoucherType" CASCADE;
DROP TABLE IF EXISTS "TallyVoucher" CASCADE;
DROP TABLE IF EXISTS "TallyVoucherEntry" CASCADE;
DROP TABLE IF EXISTS "TallyBankStatementLine" CASCADE;
DROP TABLE IF EXISTS "TallyBillAllocation" CASCADE;
DROP TABLE IF EXISTS "TallyVoucherItem" CASCADE;
DROP TABLE IF EXISTS "TallyStockItem" CASCADE;
DROP TABLE IF EXISTS "TallyGodown" CASCADE;
DROP TABLE IF EXISTS "TallyStockBatch" CASCADE;
DROP TABLE IF EXISTS "TallyVoucherRevision" CASCADE;
DROP TABLE IF EXISTS "TallyStockGroup" CASCADE;
DROP TABLE IF EXISTS "TallyStockCategory" CASCADE;
DROP TABLE IF EXISTS "TallyUnit" CASCADE;
DROP TABLE IF EXISTS "TallyStockOpening" CASCADE;
DROP TABLE IF EXISTS "TallyBankReconciliation" CASCADE;
DROP TABLE IF EXISTS "TallyTaxRate" CASCADE;
DROP TABLE IF EXISTS "TallySetting" CASCADE;
DROP TABLE IF EXISTS "TallyEmployee" CASCADE;
DROP TABLE IF EXISTS "TallyPayHead" CASCADE;
DROP TABLE IF EXISTS "TallySalaryStructureLine" CASCADE;
DROP TABLE IF EXISTS "TallyAttendanceRecord" CASCADE;
DROP TABLE IF EXISTS "TallyPayrollRun" CASCADE;
DROP TABLE IF EXISTS "TallyPayrollLine" CASCADE;
DROP TABLE IF EXISTS "TallyBackup" CASCADE;
ALTER INDEX "BookkeepingBankReconciliation_tallyCompanyId_bankLedgerId_state" RENAME TO "BookkeepingBankReconciliation_tallyCompanyId_bankLedgerId_s_idx";
ALTER INDEX "BookkeepingBankStatementLine_tallyCompanyId_bankLedgerId_date_i" RENAME TO "BookkeepingBankStatementLine_tallyCompanyId_bankLedgerId_da_idx";
ALTER INDEX "BookkeepingVoucher_tallyCompanyId_voucherTypeId_voucherNumber_k" RENAME TO "BookkeepingVoucher_tallyCompanyId_voucherTypeId_voucherNumb_key";
