/**
 * GST reminders — surfaces return filings that are due within DUE_SOON_DAYS
 * (default 3) or overdue, writes idempotent bell notifications to the GST
 * profile's assignee, and (when SMTP is configured) lets the operator shoot
 * a one-click reminder email to the client's address on record.
 *
 * The business rule follows the TDS reminder pattern (see
 * backend/src/modules/tds/reminders.ts): dedupe on
 * `notification.entityType = 'gst_reminder' + entityId = <stable key>`, so
 * the scheduler can tick every few hours without spamming the bell. For
 * every (client, kind, period) that enters the window, exactly one
 * notification is written, and never again until the window closes
 * (filing complete, period rolls over, or dueDate is extended).
 *
 * Dashboard parity: the three states this module emits reminders for are
 * the same three the dashboard shows as `due` or `overdue`, resolved via
 * `createRuleResolver` so the CBIC calendar + per-period overrides are
 * respected without duplicating the lookup.
 */
import type { PrismaClient } from '@prisma/client'
import { prisma as defaultPrisma } from '../../lib/prisma.js'
import { notifyUser } from '../../platform/notify.js'
import { mailConfigured, sendMail } from '../../lib/mailer.js'
import { ApiError } from '../../lib/http.js'
import { createRuleResolver, type FilingFrequency, type ReturnKind } from './dueDate.js'

const DUE_SOON_DAYS = 3
const TICK_MS = 6 * 60 * 60 * 1000

/**
 * Return kinds the reminder stream + dashboard panel surface. GSTR-2B is
 * deliberately excluded: it is auto-generated by the GSTN portal on the
 * 14th every month, so no human action is tied to its "due date" — the
 * 16th-of-month reminder was pure noise. GSTR-2B still shows on the main
 * dashboard grid for status visibility; it just doesn't fire reminders.
 */
const REMINDED_KINDS: ReturnKind[] = ['GSTR1', 'GSTR3B']

/**
 * Roles whose active users also receive every GST reminder bell,
 * alongside the GST profile's assigned employee + reviewer. Firm
 * leadership asked to see what's about to be due across all clients,
 * not just the ones they personally own.
 *
 * Add 'dept_manager' here if you want senior associates to see them too.
 * We dedupe per-user so an admin who's also the assigned employee only
 * gets one bell, not two.
 */
const REMINDED_ROLES = ['md', 'hr_admin']

const KIND_LABEL: Record<ReturnKind, string> = {
  GSTR1: 'GSTR-1', GSTR2B: 'GSTR-2B / IMS', GSTR3B: 'GSTR-3B',
}

/** YYYY-MM-DD in IST, independent of the host timezone. */
function todayIst(): string {
  return new Date(Date.now() + 330 * 60 * 1000).toISOString().slice(0, 10)
}
function addDays(iso: string, days: number): string {
  const d = new Date(`${iso}T00:00:00Z`)
  d.setUTCDate(d.getUTCDate() + days)
  return d.toISOString().slice(0, 10)
}
function fmt(iso: string): string {
  return new Date(`${iso}T00:00:00Z`).toLocaleDateString('en-IN', {
    day: 'numeric', month: 'short', year: 'numeric', timeZone: 'UTC',
  })
}

export interface UpcomingItem {
  key: string
  caseId: string | null
  clientId: string
  clientName: string
  clientEmail: string | null
  gstin: string
  assignedEmployeeId: string | null
  reviewerEmployeeId: string | null
  kind: ReturnKind
  period: string
  dueDate: string
  state: 'due' | 'overdue'
  daysToDue: number
}

/**
 * Walk every active GST profile for a given period, resolve each return's
 * (status, due date) via the shared rule resolver, and return the rows that
 * are either `due` within DUE_SOON_DAYS or already `overdue`. Called by
 * both the HTTP endpoint (which filters by the operator's visible clients)
 * and the scheduler (which runs org-wide).
 *
 * The `clientIdFilter` is applied by the caller — the compute step is
 * scope-agnostic so the scheduler can reach every client even when no
 * operator session exists.
 */
export async function computeUpcoming(
  prisma: PrismaClient,
  opts: { period?: string; today?: string; clientIdFilter?: string[] } = {},
): Promise<UpcomingItem[]> {
  const today = opts.today ?? todayIst()
  const period = opts.period ?? today.slice(0, 7)
  const windowEnd = addDays(today, DUE_SOON_DAYS)

  const profiles = await prisma.gstProfile.findMany({
    where: {
      deletedAt: null,
      active: true,
      // Per-client opt-out: a profile with remindersEnabled=false drops
      // out of the Upcoming panel AND the scheduled bell notifications.
      // Status columns on the main grid are untouched (that still reads
      // computePeriodState for display) — this flag only silences the
      // reminder stream.
      remindersEnabled: true,
      ...(opts.clientIdFilter ? { clientId: { in: opts.clientIdFilter } } : {}),
    },
    include: { client: { select: { id: true, companyName: true, email: true } } },
  })
  if (profiles.length === 0) return []

  const cases = await prisma.partnershipCase.findMany({
    where: {
      deletedAt: null,
      kind: { in: ['GSTR1', 'GSTR2B', 'GSTR3B'] },
      period,
      clientId: { in: profiles.map((p) => p.clientId) },
    },
    select: { id: true, clientId: true, kind: true, status: true, dueDate: true },
  })
  const caseByKey = new Map<string, (typeof cases)[number]>()
  for (const c of cases) caseByKey.set(`${c.clientId}::${c.kind}`, c)

  const resolver = await createRuleResolver(prisma)
  const out: UpcomingItem[] = []

  for (const p of profiles) {
    const freq = p.filingFrequency as FilingFrequency
    // Quarterly clients don't owe anything outside quarter-end months.
    if (freq === 'quarterly') {
      const mo = Number(period.slice(5, 7))
      if (![3, 6, 9, 12].includes(mo)) continue
    }
    for (const kind of REMINDED_KINDS) {
      const c = caseByKey.get(`${p.clientId}::${kind}`)
      if (c?.status === 'COMPLETED') continue
      const due = c?.dueDate ?? await resolver.dueDateFor(period, kind, freq)
      if (!due) continue
      // In window = (due in [today, today+N]) OR overdue (due < today).
      let state: 'due' | 'overdue' | null = null
      if (due < today) state = 'overdue'
      else if (due <= windowEnd) state = 'due'
      if (!state) continue
      // Days remaining — negative for overdue, 0 for today, 1-N for due.
      const daysToDue = Math.round((Date.parse(`${due}T00:00:00Z`) - Date.parse(`${today}T00:00:00Z`)) / 86_400_000)
      out.push({
        key: `gst:${p.clientId}:${kind}:${period}:${state}`,
        caseId: c?.id ?? null,
        clientId: p.clientId,
        clientName: p.client.companyName,
        clientEmail: p.client.email ?? null,
        gstin: p.gstin,
        assignedEmployeeId: p.assignedEmployeeId ?? null,
        reviewerEmployeeId: p.reviewerEmployeeId ?? null,
        kind,
        period,
        dueDate: due,
        state,
        daysToDue,
      })
    }
  }

  // Overdue first (negative daysToDue), then due soon.
  out.sort((a, b) => a.daysToDue - b.daysToDue)
  return out
}

/**
 * Scheduler tick. For every org-wide upcoming return, fans out ONE bell
 * notification to:
 *   - the GST profile's assigned employee (the person filing)
 *   - the reviewer, if set (the second pair of eyes)
 *   - every active user holding a role in REMINDED_ROLES (firm leadership)
 *
 * Deduped per (userId, entityId) so repeated ticks never fire a second
 * time for the same (user, client, kind, period, state) pair, AND an
 * admin who is also the assigned employee only gets one bell. Returns
 * the count actually fired.
 */
export async function sendGstReminders(prisma: PrismaClient = defaultPrisma): Promise<number> {
  const items = await computeUpcoming(prisma)
  if (items.length === 0) return 0

  // Resolve the admin user IDs ONCE per tick — firm leadership rarely
  // changes; one query per 6-hour tick is cheaper than N per reminder.
  const adminUsers = await prisma.user.findMany({
    where: {
      role: { code: { in: REMINDED_ROLES } },
      isActive: true,
      deletedAt: null,
    },
    select: { id: true },
  })
  const adminUserIds = adminUsers.map((u) => u.id)

  // Resolve assignee + reviewer employee IDs to user IDs, batched. Avoids
  // one DB roundtrip per item.
  const employeeIds = new Set<string>()
  for (const i of items) {
    if (i.assignedEmployeeId) employeeIds.add(i.assignedEmployeeId)
    if (i.reviewerEmployeeId) employeeIds.add(i.reviewerEmployeeId)
  }
  const employeeUsers = await prisma.user.findMany({
    where: { employeeId: { in: Array.from(employeeIds) }, isActive: true, deletedAt: null },
    select: { id: true, employeeId: true },
  })
  const userIdByEmployeeId = new Map(employeeUsers.map((u) => [u.employeeId ?? '', u.id]))

  // Build the delivery list — one row per (user, item). The scheduler now
  // targets up to 2 + adminCount users per return; the dedup query below
  // skips any (user, entityId) that already fired.
  const deliveries: { userId: string; item: UpcomingItem }[] = []
  for (const i of items) {
    const recipients = new Set<string>()
    const assignedUserId = i.assignedEmployeeId ? userIdByEmployeeId.get(i.assignedEmployeeId) : null
    if (assignedUserId) recipients.add(assignedUserId)
    const reviewerUserId = i.reviewerEmployeeId ? userIdByEmployeeId.get(i.reviewerEmployeeId) : null
    if (reviewerUserId) recipients.add(reviewerUserId)
    for (const u of adminUserIds) recipients.add(u)
    for (const userId of recipients) deliveries.push({ userId, item: i })
  }

  if (deliveries.length === 0) return 0

  // Per-user dedup — fetch existing (userId, entityId) pairs in one query.
  const existing = await prisma.notification.findMany({
    where: {
      entityType: 'gst_reminder',
      userId: { in: Array.from(new Set(deliveries.map((d) => d.userId))) },
      entityId: { in: Array.from(new Set(deliveries.map((d) => d.item.key))) },
    },
    select: { userId: true, entityId: true },
  })
  const sentKeys = new Set(existing.map((e) => `${e.userId}::${e.entityId}`))

  let sent = 0
  for (const { userId, item: i } of deliveries) {
    if (sentKeys.has(`${userId}::${i.key}`)) continue
    const title = i.state === 'overdue'
      ? `${KIND_LABEL[i.kind]} overdue — ${i.clientName}`
      : `${KIND_LABEL[i.kind]} due soon — ${i.clientName}`
    const body = i.state === 'overdue'
      ? `${KIND_LABEL[i.kind]} for ${i.period} was due ${fmt(i.dueDate)} (${Math.abs(i.daysToDue)} day${Math.abs(i.daysToDue) === 1 ? '' : 's'} overdue).`
      : `${KIND_LABEL[i.kind]} for ${i.period} is due ${fmt(i.dueDate)}${i.daysToDue === 0 ? ' — today' : ` (in ${i.daysToDue} day${i.daysToDue === 1 ? '' : 's'})`}.`
    const actionUrl = i.caseId
      ? `/workstation/registration/gst?caseId=${i.caseId}`
      : `/workstation/registration/gst?client=${i.clientId}&kind=${i.kind}&period=${i.period}`
    await notifyUser({
      userId,
      type: 'gst_reminder',
      module: 'workstation',
      title,
      body,
      entityType: 'gst_reminder',
      entityId: i.key,
      actionUrl,
    })
    sentKeys.add(`${userId}::${i.key}`)
    sent++
  }
  return sent
}

/** Wire the scheduler at server boot. No-op in tests. */
export function startGstReminderScheduler(prisma: PrismaClient): void {
  if (process.env.NODE_ENV === 'test') return
  const tick = () => sendGstReminders(prisma)
    .then((n) => { if (n) console.log(`[gst] ${n} reminder${n === 1 ? '' : 's'} sent`) })
    .catch((e) => console.error('[gst] reminders', e))
  // First tick a few seconds after boot so a cold start doesn't block
  // startup health checks.
  setTimeout(tick, 15_000)
  setInterval(tick, TICK_MS)
  console.log('[gst] reminder job armed — checks GST deadlines every 6 hours')
}

/**
 * Fire an email reminder to the client. Uses the firm's SMTP config
 * (see mailer.ts). The subject + body are templated here and the operator
 * can override before sending — the UI sends whatever text comes back on
 * the request. `email` defaults to the client record's email; the UI can
 * override it per send for one-off addresses.
 */
export interface SendClientReminderInput {
  caseId?: string | null
  clientId: string
  kind: ReturnKind
  period: string
  dueDate: string
  subject: string
  body: string
  to: string
  cc?: string[]
}
export interface SendClientReminderResult {
  messageId: string
  to: string
  sentAt: string
}

export async function sendClientReminder(
  prisma: PrismaClient,
  input: SendClientReminderInput,
  actorUserId: string | null,
): Promise<SendClientReminderResult> {
  if (!mailConfigured()) {
    throw ApiError.unprocessable(
      'mail_not_configured',
      'SMTP is not set up on this server. Ask your admin to configure SMTP_HOST / SMTP_USER / SMTP_PASS in settings before sending reminders.',
    )
  }
  const client = await prisma.client.findFirst({
    where: { id: input.clientId, deletedAt: null },
    select: { id: true, companyName: true, email: true, organisationId: true },
  })
  if (!client) throw ApiError.notFound('No such client.')
  const to = (input.to || client.email || '').trim()
  if (!to || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(to)) {
    throw ApiError.badRequest('Recipient email is missing or invalid.')
  }
  const subject = input.subject?.trim() || defaultReminderSubject({ clientName: client.companyName, kind: input.kind, period: input.period, dueDate: input.dueDate })
  const body = input.body?.trim() || defaultReminderBody({ clientName: client.companyName, kind: input.kind, period: input.period, dueDate: input.dueDate })

  const messageId = await sendMail({
    to: [to],
    cc: input.cc?.filter(Boolean),
    subject,
    text: body,
  })

  // Audit-stamp: a notification row with a stable key so a second send to
  // the same (case/kind/period) is distinguishable in history. Not deduped —
  // the operator may legitimately send a second nudge later.
  const sentAtIso = new Date().toISOString()
  await prisma.notification.create({
    data: {
      userId: actorUserId ?? '',
      type: 'gst_reminder_sent',
      module: 'workstation',
      title: `Reminder sent — ${subject}`,
      body: `To ${to}. ${KIND_LABEL[input.kind]} for ${input.period}.`,
      entityType: 'gst_reminder_sent',
      entityId: `gst_sent:${input.clientId}:${input.kind}:${input.period}:${sentAtIso}`,
      actionUrl: input.caseId ? `/workstation/registration/gst?caseId=${input.caseId}` : null,
    },
  }).catch(() => undefined) // best-effort — the mail already went out

  return { messageId, to, sentAt: sentAtIso }
}

export function defaultReminderSubject(opts: { clientName: string; kind: ReturnKind; period: string; dueDate: string }): string {
  return `Reminder: ${KIND_LABEL[opts.kind]} for ${opts.period} due on ${fmt(opts.dueDate)}`
}

export function defaultReminderBody(opts: { clientName: string; kind: ReturnKind; period: string; dueDate: string }): string {
  return [
    `Dear ${opts.clientName},`,
    '',
    `This is a reminder that your ${KIND_LABEL[opts.kind]} return for the period ${opts.period} is due on ${fmt(opts.dueDate)}.`,
    '',
    'Please share any pending documents (invoices, bank statements, purchase bills, expense vouchers) at the earliest so we can prepare and file the return on time.',
    '',
    'If the documents have already been shared, kindly disregard this message.',
    '',
    'Regards,',
    'Compliance team',
  ].join('\n')
}
